// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:3dMprToggle': typeof import('virtual:vite-icons/carbon/3d-mpr-toggle')['default']
    'CarbonDicomOverlay': typeof import('~icons/carbon/dicom-overlay')['default']
    'CarbonHome': typeof import('~icons/carbon/home')['default']
    'CarbonLanguage': typeof import('~icons/carbon/language')['default']
    'CarbonLogoGithub': typeof import('~icons/carbon/logo-github')['default']
    'CarbonMoon': typeof import('~icons/carbon/moon')['default']
    'CarbonPedestrian': typeof import('~icons/carbon/pedestrian')['default']
    'CarbonSun': typeof import('~icons/carbon/sun')['default']
    'CarbonWarning': typeof import('~icons/carbon/warning')['default']
    'Footer': typeof import('F:/vitesse-main/src/components/Footer.vue')['default']
  }
}

export {}
