// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:3dMprToggle': typeof import('virtual:vite-icons/carbon/3d-mpr-toggle')['default']
    'CarbonDicomOverlay': typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    'CarbonHome': typeof import('virtual:vite-icons/carbon/home')['default']
    'CarbonLanguage': typeof import('virtual:vite-icons/carbon/language')['default']
    'CarbonLogoGithub': typeof import('virtual:vite-icons/carbon/logo-github')['default']
    'CarbonMoon': typeof import('virtual:vite-icons/carbon/moon')['default']
    'CarbonPedestrian': typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    'CarbonSun': typeof import('virtual:vite-icons/carbon/sun')['default']
    'CarbonWarning': typeof import('virtual:vite-icons/carbon/warning')['default']
    'Footer': typeof import('./src/components/Footer.vue')['default']
    'Quadrate': typeof import('./src/components/ThreeJs/Quadrate.vue')['default']
  }
}

export {}
